import Card from "../components/Card";

export const products = [
  {
    id: 1,
    title: "Astor Wafer Stick Double Cokelat 40g",
    description: "Deskripsi singkat produk A",
    category: "Manis",
    stok: 15,
    diskon: 10,
    harga: 12500,
    imageUrl: "img/Astor Wafer Stick Double Cokelat 40g.jpg",
  },
  {
    id: 2,
    title: "Chacha Cokelat Susu 20g",
    description: "Deskripsi singkat produk B",
    category: "Manis",
    stok: 20,
    diskon: 10,
    harga: 6100,
    imageUrl: "img/Chacha Cokelat Susu 20g.jpg",
  },
  {
    id: 3,
    title: "Gery Malkist Salut Cokelat 100g",
    description: "Deskripsi singkat produk C",
    category: "Manis",
    stok: 16,
    diskon: 5,
    harga: 7000,
    imageUrl: "img/Gery Malkist Salut Cokelat 100g.jpg",
  },
  {
    id: 4,
    title: "Oreo Space Dunk Biskuit Sandwich Stroberi 110g",
    description: "Deskripsi singkat produk C",
    category: "Manis",
    stok: 16,
    diskon: 10,
    harga: 9800,
    imageUrl: "img/Oreo Space Dunk Biskuit Sandwich Stroberi 110g.jpg",
  },
  {
    id: 5,
    title: "Roma Malkist Abon Crackers 105g",
    description: "Deskripsi singkat produk C",
    category: "Asin",
    stok: 16,
    diskon: 10,
    harga: 8500,
    imageUrl: "img/Roma Malkist Abon Crackers 105g.jpg",
  },
  {
    id: 6,
    title: "Roma Malkist Cracers 105g",
    description: "Deskripsi singkat produk C",
    category: "Asin",
    stok: 16,
    diskon: 10,
    harga: 9000,
    imageUrl: "img/Roma Malkist Cracers 105g.jpg",
  },
  {
    id: 7,
    title: "Roma Sari Gandum Biskuit 149g",
    description: "Deskripsi singkat produk C",
    category: "Manis",
    stok: 16,
    diskon: 10,
    harga: 10000,
    imageUrl: "img/Roma Sari Gandum Biskuit 149g.jpg",
  },
  {
    id: 8,
    title: "Garuda Kacang Atom Pedas 100 g",
    description:
      "Snack kacang tanah bersalut rasa pedas dengan tekstur renyah pada bagian luar dan dalam berbentuk bulat yang pas dalam satu gigitan",
    category: "Pedas",
    stok: 19,
    diskon: 10,
    harga: 11300,
    imageUrl: "img/Garuda Kacang Atom Pedas 100 g.jpg",
  },
  {
    id: 9,
    title: "Oishi Kraker Udang Pedas 130 g",
    description: "Deskripsi singkat produk C",
    category: "Pedas",
    stok: 22,
    diskon: 10,
    harga: 15500,
    imageUrl: "img/Oishi Kraker Udang Pedas 130 g.jpg",
  },
  {
    id: 10,
    title: "Garuda Rosta Kacang Panggang Pedas 70 g",
    description: "Snack kacang tanah bersalut dengan rasa pedas",
    category: "Pedas",
    stok: 22,
    diskon: 10,
    harga: 11600,
    imageUrl: "img/Garuda Rosta Kacang Panggang Pedas 70 g.jpg",
  },
];
